#include "CPU.h"


CPU::CPU() : _instructions
{
	  { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
}
{
}