#include "CPU.h"




CPU::CPU()  
	: m_registers()
	, m_instructions
{
	  { "NOP", 1, 1, &InstructionFunctions::NOP }
	, { "LD BC", 3, 3, &InstructionFunctions::LD_BC_nn }
	, { "LD (BC) A", 1, 2, &InstructionFunctions::LD_mBC_A }
	, { "INC BC", 1, 2, &InstructionFunctions::INC_BC }
	, { "INC B", 1, 1, &InstructionFunctions::INC_B }
	, { "DEC B", 1, 1, &InstructionFunctions::DEC_B }
	, { "LD B", 1, 2, &InstructionFunctions::LD_B_n }
	, { "RLCA", 1, 1, &InstructionFunctions::RLCA }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "LD DE", 3, 3, &InstructionFunctions::LD_DE_nn }
	, { "LD (DE) A", 1, 2, &InstructionFunctions::LD_mDE_A }
	, { "INC DE", 1, 2, &InstructionFunctions::INC_DE }
	, { "INC D", 1, 1, &InstructionFunctions::INC_D }
	, { "DEC D", 1, 1, &InstructionFunctions::DEC_D }
	, { "LD D", 1, 2, &InstructionFunctions::LD_D_n }
	, { "RLA", 1, 1, &InstructionFunctions::RLA }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "LD HL", 3, 3, &InstructionFunctions::LD_HL_nn }
	, { "LD (HL+) A", 1, 2, &InstructionFunctions::LD_mHLinc_A }
	, { "INC HL", 1, 1, &InstructionFunctions::INC_HL }
	, { "INC H", 1, 1, &InstructionFunctions::INC_H }
	, { "DEC H", 1, 1, &InstructionFunctions::DEC_H }
	, { "LD H", 1, 2, &InstructionFunctions::LD_H_n }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "LD SP", 3, 3, &InstructionFunctions::LD_SP_nn }
	, { "LD (HL-) A", 1, 2, &InstructionFunctions::LD_mHLdec_A }
	, { "INC SP", 1, 2, &InstructionFunctions::INC_SP }
	, { "INC (HL)", 1, 3, &InstructionFunctions::INC_mHL }
	, { "DEC (HL)", 1, 3, &InstructionFunctions::DEC_mHL }
	, { "LD (HL)", 1, 3, &InstructionFunctions::LD_mHL_n }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
	, { "TEST", 1, 1, &InstructionFunctions::LoadToRegister }
}
{
}