name: Build Emulator

on: 
  push:
    branches:
      - main

env:
  SOLUTION_FILE_PATH: .\build\YAGE.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          # This one is not needed, as it is the default value anyway.
          vcpkgDirectory: '${{ github.workspace }}/build'
          vcpkgJsonGlob: '**/vcpkg.json'
          
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
      - name: Install Zig 0.13
        run: |
          choco install zig --version=0.13.0

      - name: Build Zig Kernel
        run: |
          cd build
          zig build kernel --summary all -Doptimize=Debug
