name: Build and Test Emulator

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vulkan SDK
        run: |
          $ErrorActionPreference = 'Stop'
          $vulkanSdkUrl = 'https://sdk.lunarg.com/sdk/download/1.3.268.0/windows/VulkanSDK-1.3.268.0-Installer.exe'
          $installerPath = 'C:\VulkanSDK-Installer.exe'
          Invoke-WebRequest -Uri $vulkanSdkUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -ArgumentList '/quiet', '/install' -Wait
          Remove-Item -Path $installerPath

      - name: Install Zig 0.13
        run: |
          choco install zig --version=0.13.0

      - name: Install Visual Studio 2022
        run: |
          choco install visualstudio2022buildtools
          choco install visualstudio2022-workload-vctools

      - name: Install Google Test
        run: |
          choco install googletest

      - name: Build Zig Kernel
        run: |
          cd build
          zig build kernel --summary all -Doptimize=Debug

      - name: Build Main Project
        run: |
          msbuild /m /p:Configuration=Release YAGE.sln
