name: Build Emulator

on: 
  push:
    branches:
      - main

env:
  SOLUTION_FILE_PATH: .\build\YAGE.sln
  BUILD_CONFIGURATION: Release
  VCPKG_INSTALLED_DIR: .\build\vcpkg_installed
  VCPKG_DEFAULT_TRIPLET: x64-windows-static

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: './build/vcpkg'
          vcpkgGitCommitId: 'b02e341c927f16d991edbd915d8ea43eac52096c'
          # Run vcpkg with the command specified by the `runVcpkgFormatString` input.
          runVcpkgInstall: true
          vcpkgJsonGlob: './build/vcpkg.json'

      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
  
      - name: Integrate vcpkg with MSBuild
        run: |
          ./build/vcpkg/vcpkg integrate install

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} `
                  /p:VcpkgRoot=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }} `
                  /p:VcpkgInstalledDir=${{env.VCPKG_INSTALLED_DIR}} `
                  /p:VcpkgTriplet=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }} `
                  ${{env.SOLUTION_FILE_PATH}}
        
      - name: Install Zig 0.13
        run: |
          choco install zig --version=0.13.0

      - name: Build Zig Kernel
        run: |
          cd build
          zig build kernel --summary all -Doptimize=Debug
